language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit --color --coverage-clover ./tests/logs/clover.xml tests

after_success:
  - travis_retry php vendor/bin/coveralls -v
